sudo: required

services:
  - docker

language: node_js

node_js:
  - node

cache: yarn

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=sstrigler/smrtrpck
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO

env:
  global:
    - secure: wcUENzt/73oTdya6eh+JLA1/m93y1ZtkJxaEmSqHpQq8lQ4+jY+Z5yxkrSTw3wy8UgOzLmGz2Icm1GPzGqfFsUatKiIOoysh5K12NpPsDX7DJlSWBN0vCEYb0YtKYCrtMlBKFubZ22DrVE9WLyRyeq+AoIUpw1d3+DpJZx/B/0DqvuGV8g90/n/qIcutr3oa3kMdCe6R64/1u9FwK/GQ/IjP+PyN13mFxk+tRsRPkdarOZK1ak3T22yJmrz0BPVJzggbcn55U96kBe3dqJNejmyo9qkM5hp3pzb8d1jLdO09/poGsDbsSHNBPP8NKy8c6QKwyDGuZJr++73Ntnr42P42sP63Jb0itvftuG7zYuqAz3nwXieujEzM8oCh+nbcvfahsJFpyDmXnUvjhzQs59FQDbkiuGTMZQyVPENqGkOZoVnUlIjPLJE12+EEPP35DXF9g77m6t3LHU8Y0a1gsyp/1H46Y90AlegIAf3LZcL85o3Nlto/iBPK8wi7wcUlPnhH9La8m8jJAGpQfrGgh3G6MNI6kPXyJTH9p+n/oRj/k2ho4KFGQVfIwLG92wNpLfadWujHilSQk02LTS06bf62btMUV8ZHJca9v5+ov+egK3guknpXyqfmLFNH9captsBbT9IOMXcx3HpCP5LxcLmFmwA+I64suABGn6mpayU=
    - secure: nReOjS1Hf+LCvhBckv8NSG8r/rAZHIfgJIK2+TpkDPpBxlFGEVsej2jPEAZ5SjtJNDIeSQWHzrPaOoAFIvPxa97VQq88S2BUTGi3Y9by7Qp8Tuw+goJevrt9Amg4vkLs+vSjGwrnTaRKMIDe84AcTiKKGuHzIr//YeK6kYxEE550FYujyYEuKU6L1TXW4+cGvYbT3f4LmMQhrjabmp/ttkTLFbOPwtykXn89CkS4Z/nSnDogJLMdYF1x8X06GuTqX9t5DhBs7WQyCNzZfWPMBRwLLYmf0/3xENQRAKzb4zNsZr1+8c6/Y+jgWtecqfhrh5T91yeDaHHnyWbgYU+9rgR44HXWBKxoRWVjzf07zpfCiKs06lA69GGNAzADNhIOEwdIO8rE3uIK0bg1L/D2iHeG2VnNyFsU2QehXm8tMzIXqrYaKFG0VuFEdtCP7qz5qOOZwG1vPR6uE6G2fNLao57Psi4Tv4xh9bUEAPFIlGWpAjSbE1wtTvPtE4YKJisU4OPZcf1v4suAqQ6ASCO0Bw2iJDCtC2ZZ6f0nkVOXIlzO1+sWgTUynMfxoPOzg3BtIUNIjhl1ePKDJJ/EpN8qLQe6dtTXbN0i9VTW7q3QBIbRUoO5YFpxv0wofHMKj7u4aZFLo/EpZVNUqSWpqbJlveRt7EGF1O5HLsP79LkkDR4=
    - secure: Zz5LChu1WvQSCE6XwCqEA2WZLnWEhs7A2cQqDjpTRDut+Zcww8+NlyZ9sYgtSWlAs67Vcn12HtioGWKo6wJPpHRWDu4IAo9XOoE9HWNQsVCvFf0F2UjVhAskYcyZH1ozCuMOoRfD+16RZ8J5ERzBGoaMzIVFrCDJoKfG8yDJRrCPbU9aYWx9pPpFmcYEX9WzXBggRpBYJ313Dlv8XGpsJmMXyL3t6r9g+DUp7P1lUdP4hby7zcLJUdmN4hRjd4ZKLWpjGEwN6mqd9Kjb9MscKpefpx0mLGNOW5DTP7uryE9PoAVZVs/Y4NKVrN6+CNFgQsJmjDM1calqijQKOpIX8xbJJd+yjUmjmZiHkDwe8mb+8/AXq2uc+2s2/0L+39n9mijfiNKkpDWHh/y4hbtN0UGdd04ZZHbAPa2fuyhnuMBpXYP4snk0ZVFUuXLeOXq6XJoWbFe8g8iQ8S8xc04NMFMgYs+hhJHab70AAfgjJsQ9PQkEVA/26TmY2JXrcb0RFCtsN7tBotzf2tk2JbvN3EfZw/r1kQdpzMoIpXBIxy+qx+228MK29t3s+91kSKqGUrqoero3lMaVDuMe5KeG3AG4HwjAuOZxCblolr6dPL0izc/qOZ2zpw3nygxxzVHtbRlJ8IBq21DQii+ReSlVf2sfh1sewl568s7Vg6mSiIM=
    - COMMIT=${TRAVIS_COMMIT::8}
